# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2397377a7efb1098a5d4842e57106b89c6f237f2f8aeff6d8bcb8722e215aacb0bf8cec5146398b77d717c5ea7275613a817ccff919ee705b6306b90ce61bf4d

test:
  secret_key_base: c73ea9059cb29c43c6c307b14d331a1c63105333181e05878bf1db523e838b286b54ce3b97715c4cf40a595e71449cbb98ff9214dfdefbbaa7f527f3fd9e372e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
